version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./yii-application/web:/var/www/html
      - ./vue-frontend/dist:/usr/share/nginx/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./yii-application/Dockerfile
    volumes:
      - ./yii-application:/app
    networks:
      - app-network

  vue:
    build:
      context: .
      dockerfile: ./vue-frontend/Dockerfile
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
